"""
All domain constants – single source of truth.

Every column name, regex pattern, alias, and magic string used
across the project is defined here. Import from this module
instead of hardcoding strings.
"""

from typing import Dict, FrozenSet, List
import re

# ─────────────────────────────────────────────────────────────────────────
# TOC Column Definitions
# ─────────────────────────────────────────────────────────────────────────

# 14 columns that must come from the input TOC file
TOC_INPUT_COLS: List[str] = [
    'FROM', 'TO', 'GN', 'UN',
    'RT-PT-N', 'RT-PT-R', 'RT-TC',
    'OV-PT-N', 'OV-PT-R', 'OV-TC', 'OV-SET',
    'ISO', 'ISO-TC', 'YR',
]

# 13 columns added as blanks – generated by the processing pipeline
TOC_BLANK_COLS: List[str] = [
    'NEW-LOCK', 'FROM-TO', 'DIR', 'END', 'RD', 'FRTO',
    'ISO-PT-N', 'ISO-PT-R', 'TCK', 'NEW-LCK2',
    'SH-DISP-LIT', 'MN-MOVT-LIT', 'SUB-MOVT-LIT',
]

# All TOC columns in canonical order
ALL_TOC_COLS: List[str] = TOC_INPUT_COLS + TOC_BLANK_COLS

# Extra optional columns read from the input TOC (crank handle / signal aspects)
TOC_EXTRA_COLS: List[str] = ['CH', 'HG', 'HHG', 'DG']

# Columns that are always string type
STR_COLS: List[str] = [
    'FROM', 'TO', 'GN', 'RT-TC', 'OV-TC',
    'RT-PT-N', 'RT-PT-R', 'OV-PT-N', 'OV-PT-R',
    'ISO', 'ISO-TC', 'UN', 'OV-SET', 'YR',
]

# Point columns (underscore → '/' separator)
PT_COLS: List[str] = ['RT-PT-N', 'RT-PT-R', 'OV-PT-N', 'OV-PT-R', 'ISO']

# Track-circuit columns (carry /AXT suffix)
TC_COLS: List[str] = ['RT-TC', 'OV-TC', 'ISO-TC']

# Junk column names to silently drop (normalized uppercase)
DROP_COL_NAMES: FrozenSet[str] = frozenset({
    'SNO', 'SN', 'SLNO', 'SRNO', 'SERIALNO', 'SERIALNUMBER', 'NO',
    'SIGNALROUTE', 'SIGNALROUT', 'SGROUP', 'GROUP',
    'BUTTONSIG', 'BUTTONSIG.',  # MRN "BUTTON SIG." — signal+approach note, GN comes from SIG. RTE
})

# ─────────────────────────────────────────────────────────────────────────
# Column Aliases – display-name → internal-name
# ─────────────────────────────────────────────────────────────────────────

COL_ALIASES: Dict[str, str] = {
    # Movement columns
    'FROM': 'FROM', 'FR': 'FROM',
    'MOVEMENTFROM': 'FROM',  # MRN "MOVEMENT FROM" merged header
    'TO': 'TO',
    # Button / signal columns
    'SIGNAL': 'GN', 'GN': 'GN',
    'SIGRTE': 'GN',   # MRN "SIG. RTE" merged header (signal/CO identifier, annotations stripped in Pass 3)
    'ROUTE': 'UN', 'UN': 'UN',
    # Route points / track
    'RT-PT-N': 'RT-PT-N', 'ROUTEPOINTNORMAL': 'RT-PT-N',
    'RT-PT-R': 'RT-PT-R', 'ROUTEPOINTREVERSE': 'RT-PT-R',
    'RT-TC': 'RT-TC', 'ROUTETRACKCIRCUIT': 'RT-TC',
    # Overlap points / track
    'OV-PT-N': 'OV-PT-N', 'OVERLAPPOINTNORMAL': 'OV-PT-N',
    'OV-PT-R': 'OV-PT-R', 'OVERLAPPOINTREVERSE': 'OV-PT-R',
    'OV-TC': 'OV-TC', 'OVERLAPTRACKCIRCUIT': 'OV-TC',
    'OV-SET': 'OV-SET', 'OVERSET': 'OV-SET', 'OV SET': 'OV-SET',
    'OVERLAPSET': 'OV-SET',
    # Isolation
    'ISO': 'ISO', 'ISOLATIONPOINT': 'ISO',
    'ISO-TC': 'ISO-TC', 'ISOLATIONTRACK': 'ISO-TC',
    # Approach locking / signal aspect / gate
    'YR': 'YR', 'GATE/SIDING': 'YR', 'CONTROLGATESIDING': 'YR',
    'CONTROLGATESIDG': 'YR',  # MRN "CONTROL GATE/ SDG" merged header
    # Extra input columns: crank handle and signal aspects
    'CRANK HANDLE': 'CH', 'CRANKHANDLE': 'CH', 'CH': 'CH',
    'Y': 'HG', 'HG': 'HG', 'SIGNAL ASPECT Y': 'HG',
    'SIGNALASPECTYELLOW': 'HG',  # MRN "SIGNAL ASPECT YELLOW" merged header
    'YY': 'HHG', 'HHG': 'HHG', 'SIGNAL ASPECT YY': 'HHG',
    'DOUBLEYELLOW': 'HHG',       # MRN "DOUBLE YELLOW" column
    'G': 'DG', 'DG': 'DG', 'SIGNAL ASPECT G': 'DG',
    'GREEN': 'DG',               # MRN "GREEN" column
}

# ─────────────────────────────────────────────────────────────────────────
# Pre-compiled Regex Patterns
# ─────────────────────────────────────────────────────────────────────────

# Remove special chars not attached to alphanumeric on both sides
RE_ISOLATED_SPECIALS = re.compile(
    r'(?<![A-Za-z0-9])[^A-Za-z0-9\s]+|[^A-Za-z0-9\s]+(?![A-Za-z0-9])'
)

# Normalize column names for fuzzy matching
RE_NORMALIZE_COL = re.compile(r'[\s\-_.]')

# Noise characters in cells
RE_CELL_NOISE = re.compile(r'[ \.\-\n#@\*\?\^\$\(\)]')

# Track-circuit suffix (e.g. /AXT)
RE_TC_SUFFIX = re.compile(r'/[A-Za-z]{2,}')

# Non-alphanumeric removal
RE_NON_ALNUM = re.compile(r'[^A-Za-z0-9]')

# Check if cell has alphanumeric content
RE_HAS_ALPHA = re.compile(r'[A-Za-z]')
RE_HAS_DIGIT = re.compile(r'\d')

# Home / calling-on signal pattern
RE_HOME_SIGNAL = re.compile(r'^(S\d+|CO\d+)$')

# Numeric extraction from signal name
RE_SIGNAL_NUM = re.compile(r'\d+')

# Track circuit token pattern (e.g. 229T, 03AT, 240/250T, 238/241/252T, DMAT,
# and underscore-joined names such as 1_2T, 01_01AT used at UJN)
RE_TRACK_CIRCUIT = re.compile(
    r'^(?!AXT$)(?:[A-Z0-9]*\d[A-Z0-9]*(?:[/_][A-Z0-9]+)*|[A-Z]{2,})T$', re.IGNORECASE
)

# Characters stripped from point/TC field ends during IXL processing
STRIP_PUNCTUATION: str = r'\s.\_\n\t()DM'

# Clean patterns for cell values
CLEAN_PATTERNS: List[str] = [
    ' ', r'\.', '-', '\n', '#', '@', r'\*', r'\?',
    r'\^', r'\$', r'\(', r'\)',
]

# N/R suffix patterns for removal
NR_PATTERNS: List[str] = ['N', 'R', r'\n', r'\\n\\n']

# ─────────────────────────────────────────────────────────────────────────
# File I/O Definitions
# ─────────────────────────────────────────────────────────────────────────

EXCEL_ENGINES: Dict[str, str] = {
    '.xlsx': 'calamine',
    '.xlsm': 'calamine',
    '.xlam': 'calamine',
    '.xls': 'xlrd',
    '.ods': 'odf',
}

FILETYPES_TABLE = [
    ('Table files', '*.csv *.xlsx *.xls *.pdf'),
    ('CSV files', '*.csv'),
    ('Excel files', '*.xlsx *.xls'),
    ('PDF files', '*.pdf'),
    ('All files', '*.*'),
]

SAVE_TYPES = [
    ('CSV file', '*.csv'),
    ('Excel file', '*.xlsx'),
    ('All files', '*.*'),
]

# ─────────────────────────────────────────────────────────────────────────
# Auto-install Package Definitions
# ─────────────────────────────────────────────────────────────────────────

REQUIRED_PKGS: Dict[str, str] = {
    'pandas': 'pandas',
    'openpyxl': 'openpyxl',
    'xlrd': 'xlrd',
    'PySide6': 'PySide6',
}

OPTIONAL_PKGS: Dict[str, str] = {
    'python_calamine': 'python-calamine',
    'odf': 'odfpy',
    'pdfplumber': 'pdfplumber',
}
